apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    isDefault: true
    version: 1
    editable: true
    basicAuth: true
    basicAuthUser: admin
    basicAuthPassword: foobar
    jsonData:
      graphiteVersion: "1.1"
      tlsAuth: false
      tlsAuthWithCACert: false
  - name: Loki
    type: loki
    orgId: 1
    access: proxy
    url: http://loki:3100
    jsonData:
      maxLines: 1000
