apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:8000
    isDefault: true
    version: 1
    editable: true
  - name: Loki
    type: loki
    orgId: 1
    access: proxy
    url: http://loki:3100
    jsonData:
      maxLines: 1000
