name: Core Api Unit Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x64'
    # - name: Build and test with Pytest
    #   env:
    #     PGHOST: 127.0.0.1
    #     PGUSER: postgres
    #     RAILS_ENV: test
    #   run: |
    #     sudo apt-get -yqq install libpq-dev
    #     gem install bundler
    #     bundle install --jobs 4 --retry 3
    #     cp config/database.postgres.yml config/database.yml
    #     bundle exec rake db:test:prepare
    #     bundle exec rake spec